import * as XLSX from 'xlsx';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { ExportData } from './export-context';

type Format = 'csv' | 'xlsx' | 'pdf';

function sanitizeName(name: string): string {
  return name.replace(/[\/\\:*?"<>|]/g, '-');
}

function baseFileName(data: ExportData): string {
  const range = sanitizeName(data.dateRange.replace(/\s*–\s*|\s+-\s+/g, '-'));
  return `ProjectHub_Overview_${range}`;
}

function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function overviewTable(data: ExportData): (string | number)[][] {
  const rows: (string | number)[][] = [
    ['ProjectHub — Overview Report'],
    [`Date Range: ${data.dateRange}`],
    [`Generated: ${data.generatedAt}`],
    [`Generated By: ${data.generatedBy}`],
    [`Active View: ${data.activeTab}`],
    [],
    ['Overview Summary'],
    ['Metric', 'Value'],
    ...data.metrics.map((m) => [m.label, m.value] as (string | number)[]),
    [],
    ['Projects'],
    ['Project', 'Status', 'Total Issues', 'Open Issues', 'Completion %'],
    ...data.projects.map((p) => [p.name, p.status, p.totalIssues, p.openIssues, `${p.completionPct}%`] as (string | number)[]),
    [],
    ['Team Member Activity'],
    ['Member', 'Role', 'Assigned', 'Done', 'In Progress', 'Completion %'],
    ...data.members.map((m) => [m.name, m.role, m.assigned, m.done, m.inProgress, `${m.completionPct}%`] as (string | number)[]),
  ];
  return rows;
}

function toCSV(data: ExportData): string {
  const rows = overviewTable(data);
  return rows
    .map((row) =>
      row
        .map((cell) => {
          const s = String(cell);
          return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
        })
        .join(',')
    )
    .join('\n');
}

function sheetFromData(data: ExportData): XLSX.WorkSheet {
  const ws = XLSX.utils.aoa_to_sheet(overviewTable(data));
  ws['!cols'] = [{ wch: 14 }, { wch: 28 }, { wch: 12 }, { wch: 12 }, { wch: 12 }, { wch: 12 }];
  return ws;
}

function roundRect(doc: jsPDF, x: number, y: number, w: number, h: number, r: number) {
  doc.roundedRect(x, y, w, h, r, r);
}

export function exportData(format: Format, data: ExportData): void {
  switch (format) {
    case 'csv': {
      const csv = toCSV(data);
      const blob = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' });
      triggerDownload(blob, `${baseFileName(data)}.csv`);
      break;
    }
    case 'xlsx': {
      const wb = XLSX.utils.book_new();
      const ws = sheetFromData(data);
      XLSX.utils.book_append_sheet(wb, ws, 'Overview');
      const buf = XLSX.write(wb, { type: 'array', bookType: 'xlsx' });
      const blob = new Blob([buf], {
        type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      });
      triggerDownload(blob, `${baseFileName(data)}.xlsx`);
      break;
    }
    case 'pdf': {
      const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' });
      const pageWidth = doc.internal.pageSize.getWidth();

      roundRect(doc, 40, 40, pageWidth - 80, 70, 8);
      doc.setFillColor(238, 242, 255);
      doc.rect(40, 40, pageWidth - 80, 70, 'F');
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(16);
      doc.setTextColor(30, 41, 59);
      doc.text('ProjectHub — Overview Report', pageWidth / 2, 62, { align: 'center' });
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(100, 116, 139);
      doc.text(`Date Range: ${data.dateRange}`, pageWidth / 2, 80, { align: 'center' });
      doc.text(`Generated: ${data.generatedAt}  ·  By: ${data.generatedBy}`, pageWidth / 2, 94, { align: 'center' });
      doc.text(`Active View: ${data.activeTab}`, pageWidth / 2, 106, { align: 'center' });

      const metrics: [string, ...(string | number)[]][] = data.metrics.map((m) => [m.label, m.value]);
      autoTable(doc, {
        startY: 140,
        head: [['Overview Summary']],
        body: metrics,
        styles: { fontSize: 9, cellPadding: 4 },
        headStyles: { fillColor: [99, 102, 241], textColor: 255 },
      });
      const afterMetrics = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 14;

      autoTable(doc, {
        startY: afterMetrics,
        head: [['Project', 'Status', 'Total', 'Open', 'Completion']],
        body: data.projects.map((p) => [p.name, p.status, p.totalIssues, p.openIssues, `${p.completionPct}%`]),
        styles: { fontSize: 9, cellPadding: 4 },
        headStyles: { fillColor: [99, 102, 241], textColor: 255 },
        theme: 'striped',
      });
      const afterProjects = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 14;

      autoTable(doc, {
        startY: afterProjects,
        head: [['Member', 'Role', 'Assigned', 'Done', 'In Progress', 'Completion']],
        body: data.members.map((m) => [m.name, m.role, m.assigned, m.done, m.inProgress, `${m.completionPct}%`]),
        styles: { fontSize: 9, cellPadding: 4 },
        headStyles: { fillColor: [99, 102, 241], textColor: 255 },
        theme: 'striped',
      });

      doc.save(`${baseFileName(data)}.pdf`);
      break;
    }
  }
}

export type { Format };